require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

#追加
#expectを複数使用可能
#とりあえず10個
RSpec/MultipleExpectations:
  Max: 10

#追加
#空のブロック作成を許可
Lint/EmptyBlock:
  Enabled: false

#追加
#IndexedLetのチェックを無効
RSpec/IndexedLet:
  Enabled: false
